### PR TITLE
Added icons for exercise difficulty.

### PR DESCRIPTION
**Pull request by anekimken**
Used skiing-type icons, and added a little key above the exercises.
Spacing is not particularly pretty, so I'm open to suggestions on how to improve that in particular.

### CODE REVIEW

**Comment by comfit20** [comment]
I see, I like the skiing notation :) 
For the spacing we could play around with margin and padding: https://www.w3.org/TR/CSS2/box.html

Here is the bootstrap info about spacing: https://getbootstrap.com/docs/4.0/utilities/spacing/ And maybe badges could be used to improve the spacing. https://getbootstrap.com/docs/4.0/components/badge/ Just an idea. Let me know what you think :) Custom CSS with padding and margins should work in any case :) Let me know what you think.

**Comment by comfit20** [comment]
I think it looks better but I feel there should still be a margin between the text and the badge. Also it would be nice if the icon does not stand alone in a line. I think a layout like this would be nice for each exercise: (x is the checkbox) 
```
-----------------------------------------------------------------
|     |   text goes                                   |           |
|  x  |  here                                         |  badge    |
|     |   somewhe                                     |           | 
-----------------------------------------------------------------
```
This can be achived with some divs, flexbox stuff and css :)

**Comment by anekimken** [comment]
That sounds good. I'll give it a shot this weekend and try to get the spacing right. Thanks for pointing me in the right direction. Good way to learn!

**Comment by comfit20** [comment]
Looks better in my opinion, thanks!

Maybe we should add another spacing to make it clear which Icon belongs to which exercise. If I just see the overview its hard to see the connection between icon and exercise. (For theoretical background information: gestalt principles are the key word here: https://medium.muz.li/gestalt-principles-in-ui-design-6b75a41e9965) proximity and common region in particular.

**Comment by anekimken** [comment]
Latest commit has better grouping using borders. I'd also like to make the boxes check when the name of the exercise gets clicked.

Bonus: exercise previews!

**Comment by wirthual** [comment]
Wow, the preview is such a nice feature! 

For the text to be clickable too, I just put the inputs inside the labels and removed the for attribute in the label element. Seems to work now. But I am happy to get someone else to confirm since I dont know if anything relies on the for label. A quick test seemed to work :+1:

**Comment by anekimken** [comment]
Ah, I see. I found information about putting the input inside the label on stackexchange, but missed the elimination of the for attribute.

What do you think about the position of the preview video? I spent some time trying to move it around without success.

**Comment by wirthual** [comment]
I was also thinking about the position. I think it should be floating. Depending if it's on the upper or lower corner of the screen so the video is always fully visible. 

I think bootstrap popover https://getbootstrap.com/docs/4.0/components/popovers/ could be a good start and set the placement so auto. This way left top right or bottom is choose based on the positioning. 

Probably there are some good tutorials for working with popovers.

**Pull request merged**
